### ISSUE TITLE
how can i get cnnModel.bin file

### ISSUE THREAD

**Issue by Giligency-xl** [TSBprojects/EmotionRecognition#2]
hello ,i am try to run your application.but i finded it need a file called "cnnModel.bin",how can i get it or make it?i donnot know how to do ,i am a student , could you help me?  i'll be very greatful

**Comment by TSBprojects** [comment]
Hi! I'm kind a busy right now, but I will be happy to provide a model in the near future :)

**Comment by TSBprojects** [comment]
Here it is: [cnnModel](https://yadi.sk/d/3MKzWjJ2hVFWCQ)
